/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaMiniPlayer.java
 *
 * Created on 26/01/2010, 20:14:25
 */

package visao;

import persistencia.Banco;
import controle.MediaPlayer;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import util.PlanoDeFundo;

/**
 *
 * @author Idair F. Guido
 */
public class JFTelaMiniPlayer extends javax.swing.JFrame {

    private MediaPlayer player;

    /** Creates new form TelaMiniPlayer */
    public JFTelaMiniPlayer(MediaPlayer player) {
        this.player = player;
        setaIcon();
        initComponents();
        jsProgresso.setValue(0);
        jsVolume.setMinimum(0);
        jsVolume.setMaximum(100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlDuracao = new javax.swing.JLabel();
        jlAlbum = new javax.swing.JLabel();
        jlMusica = new javax.swing.JLabel();
        jpControl = new javax.swing.JPanel();
        jbPlayPause = new javax.swing.JButton();
        jbAnterior = new javax.swing.JButton();
        jbStop = new javax.swing.JButton();
        jbProxima = new javax.swing.JButton();
        jsVolume = new javax.swing.JSlider();
        jbTelaPrincipal = new javax.swing.JButton();
        jsProgresso = new javax.swing.JSlider();
        jlVolume = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guido's Media Player");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlDuracao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDuracao.setForeground(new java.awt.Color(204, 255, 255));
        jlDuracao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jlAlbum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlAlbum.setForeground(new java.awt.Color(204, 255, 255));
        jlAlbum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAlbum.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        jlMusica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlMusica.setForeground(new java.awt.Color(204, 255, 255));
        jlMusica.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jbPlayPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/control_play_blue.png"))); // NOI18N
        jbPlayPause.setToolTipText("Play / Pause");
        jbPlayPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPlayPauseActionPerformed(evt);
            }
        });

        jbAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/control_rewind_blue.png"))); // NOI18N
        jbAnterior.setToolTipText("Musica Anterior");
        jbAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnteriorActionPerformed(evt);
            }
        });

        jbStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/control_stop_blue.png"))); // NOI18N
        jbStop.setToolTipText("Stop");
        jbStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStopActionPerformed(evt);
            }
        });

        jbProxima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/control_fastforward_blue.png"))); // NOI18N
        jbProxima.setToolTipText("Proxima Musica");
        jbProxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProximaActionPerformed(evt);
            }
        });

        jsVolume.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jsVolumeMouseDragged(evt);
            }
        });

        jbTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/application_get.png"))); // NOI18N
        jbTelaPrincipal.setToolTipText("Voltar para tele princial.");
        jbTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTelaPrincipalActionPerformed(evt);
            }
        });

        jsProgresso.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout jpControlLayout = new javax.swing.GroupLayout(jpControl);
        jpControl.setLayout(jpControlLayout);
        jpControlLayout.setHorizontalGroup(
            jpControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpControlLayout.createSequentialGroup()
                .addComponent(jbPlayPause, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jbAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jbStop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbProxima, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlVolume)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsVolume, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jsProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );
        jpControlLayout.setVerticalGroup(
            jpControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpControlLayout.createSequentialGroup()
                .addComponent(jsProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jsVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jbTelaPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbPlayPause, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbStop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbProxima, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlVolume, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlDuracao, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jlDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpControl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(265, 227));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        Banco.disconect();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jpControl.setVisible(true);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        jpControl.setVisible(false);
    }//GEN-LAST:event_formWindowLostFocus

    private void jsVolumeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jsVolumeMouseDragged
//        BigDecimal vol = BigDecimal.valueOf(jsVolume.getValue());
//        BigDecimal perc = BigDecimal.valueOf(100);
//        BigDecimal result = vol.divide(perc, 2, RoundingMode.HALF_EVEN);
//        player.volume.setVolumeControl(result.floatValue());
        player.volume.setVolumeLevel(1, jsVolume.getValue());
        setaIconVolume();
}//GEN-LAST:event_jsVolumeMouseDragged

    private void jbTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTelaPrincipalActionPerformed
        player.estanciaTelaPrincipal();
}//GEN-LAST:event_jbTelaPrincipalActionPerformed

    private void jbStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStopActionPerformed
        if(player.isExecutando())
            player.stop();
    }//GEN-LAST:event_jbStopActionPerformed

    private void jbPlayPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlayPauseActionPerformed
        try {
            if(player.playListIsEmpty()){
                player.estanciaTelaPrincipal();
            }else{
                if(player.getNroMusicaExecutando() == -1)
                    player.play(0);
                else
                    player.play(player.getNroMusicaExecutando());
            }
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbPlayPauseActionPerformed

    private void jbAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnteriorActionPerformed
        try {
            if(!player.playListIsEmpty())
                player.musicaAnt();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbAnteriorActionPerformed

    private void jbProximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProximaActionPerformed
        try {
            if(!player.playListIsEmpty())
                player.proxMusica();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(JFTelaMiniPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbProximaActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaMiniPlayer().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAnterior;
    private javax.swing.JButton jbPlayPause;
    private javax.swing.JButton jbProxima;
    private javax.swing.JButton jbStop;
    private javax.swing.JButton jbTelaPrincipal;
    private javax.swing.JLabel jlAlbum;
    private javax.swing.JLabel jlDuracao;
    private javax.swing.JLabel jlMusica;
    private javax.swing.JLabel jlVolume;
    private javax.swing.JPanel jpControl;
    private javax.swing.JSlider jsProgresso;
    private javax.swing.JSlider jsVolume;
    // End of variables declaration//GEN-END:variables

    public void setaIcon(){
        Image img = new ImageIcon(getClass().getResource("/visao/icones/picon.png")).getImage().getScaledInstance(64, 64, Image.SCALE_DEFAULT);
        this.setIconImage(img);
        JPanel bg = new PlanoDeFundo("/visao/imagens/PlanoDeFundoMiniPlayer.jpg");
        this.setContentPane(bg);
    }

    public void setaIconVolume(){
        if(jsVolume.getValue() > 0){
            jlVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/cSom.png")));
        }else{
            jlVolume.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visao/icones/sSom.png")));
        }
    }

    public void setVolume(int valor){
        jsVolume.setValue(valor);
    }

    public void setProgresso(int valorMaximo, int valor){
        jsProgresso.setMaximum(valorMaximo);
        jsProgresso.setValue(valor);
    }

    public void setTempoDecorrido(String tempo, String musica, String album){
        jlDuracao.setText(tempo);
        jlAlbum.setText(album);
        jlMusica.setText(musica);
    }

}
